version: 2.1

workflows:
  build_each_env:
    jobs: # https://nodejs.org/ja/about/releases/
      - build:
          name: Node.js 8
          node_ver: 8  # EOL: 2019-12-31 (LTS)
      - build:
          name: Node.js 10
          node_ver: 10 # EOL: 2021-04-01 (LTS)
      - build:
          name: Node.js 11
          node_ver: 11 # EOL: 2019-06-01
      - build:
          name: Node.js 12
          node_ver: 12 # EOL: 2022-04-01 (LTS)

jobs:
  build:
    parameters:
      node_ver:
        type: integer
        default: 10
    docker:
      - image: node:<< parameters.node_ver >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup & Test
          command: npm cit
      - run:
          name: Setup & Test for Example
          command: npm cit
          working_directory: ./example
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
